version: '3.8'

services:
  kagchi-web:
    deploy:
      resources:
        limits:
          memory: "64M"
    restart: unless-stopped
    image: 'ghcr.io/kagchi/kagchi:latest-dev'
    env_file:
      - .env
    networks:
      internet:
        aliases:
          - kagchi-web.internet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kagchi-web.rule=Host(`kagchi.my.id`)"
      - "traefik.http.routers.kagchi-web.entrypoints=web,websecure"
      - "traefik.http.routers.kagchi-web.tls=true"
      - "traefik.http.routers.kagchi-web.tls.options=cloudflare@file"
      - "traefik.http.routers.kagchi-web.middlewares=cloudflare-real-ip@file"
      - "traefik.http.services.kagchi-web.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: 10.0.36.0/24
    internal: false
